In [1]:
import numpy as np

**1. ReLU- Rectified Linear Unit (Hidden Layer)**

In [2]:
def relu(x):
  return np.maximum(0,x)

In [6]:
relu(-10)

np.int64(0)

In [4]:
relu(10)

np.int64(10)

In [7]:
relu(np.array([-1,0,1,2]))

array([0, 0, 1, 2])

**2. Leaky ReLU**

In [11]:
def leaky_relu(x, alpha=0.01): #It takes two arguments
  return np.where(x>0,x,x*alpha) #where function works like a vectorized if-else.

In [9]:
leaky_relu(-5)

array(-0.05)

In [10]:
leaky_relu(np.array([-1,0,1,2]))

array([-0.01,  0.  ,  1.  ,  2.  ])

**3. ELU - Exponential Linear Unit (Hidden Layer)**

In [12]:
def elu(x,alpha=1.0):
  return np.where(x>0,x,alpha*(np.exp(x)-1))

In [13]:
elu(5)

array(5.)

In [14]:
elu(np.array([-1,0,1,2]))

array([-0.63212056,  0.        ,  1.        ,  2.        ])

**4. Sigmoid (Output and Binary Class Problem)**

In [17]:
def sigmoid(x):
  return 1 / (1+np.exp(-x))

In [18]:
sigmoid(np.array([-1,0,1,2]))

array([0.26894142, 0.5       , 0.73105858, 0.88079708])

**5. Softmax (Output Layer & Multiclass Problem)**

In [19]:
def softmax(x):
  e_x=np.exp(x-np.max(x))
  return e_x / e_x.sum(axis=0)

In [22]:
proba=softmax(np.array([-1,1,0.5]))
proba

array([0.07769558, 0.57409699, 0.34820743])

In [23]:
sum(proba)

np.float64(1.0)

**6. Swish (Hidden Layer)**

In [24]:
def swish(x,beta=1.0):
  return x*sigmoid(beta*x)

In [25]:
swish(5)

np.float64(4.966535745378576)

In [26]:
swish(np.array([-1,0,1,2]))

array([-0.26894142,  0.        ,  0.73105858,  1.76159416])

**7. Linear (Output Layer)**

In [27]:
def linear(x):
  return x

In [28]:
linear(10)

10

In [29]:
linear(-5)

-5

**8. tanh (Hyperbolic Tangent)**

In [31]:
np.tanh(10)

np.float64(0.9999999958776927)

In [32]:
def tanh(x):
  return np.tanh(x)

In [33]:
tanh(10)

np.float64(0.9999999958776927)

In [34]:
tanh([-1,0,1,2])

array([-0.76159416,  0.        ,  0.76159416,  0.96402758])

In [35]:
import math
def tanh(x):
  result=(math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))
  return result

In [36]:
tanh(-1)

-0.7615941559557649